dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  chrome: stable
  firefox: latest

cache:
  directories:
     - ./node_modules

install:
  - npm ci

script:
  - npm run build
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run test -- --no-watch --no-progress --browsers=FirefoxHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

before_deploy:
  - cd dist/scroll-spy

deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: npm
  email: elshinnaweyom@gmail.com
  api_key: "$NPM_TOKEN"
